# Generated by Django 2.2.1 on 2019-05-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190531_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
