# Generated by Django 2.2.1 on 2019-05-31 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190531_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.Faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rank',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Part_Time', 'Part_Time'), ('Professor', 'Professor')], max_length=20),
        ),
    ]
